version: '3.8'
services:
  db:
    image: postgres
    restart: always
    env_file: .env_prod
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '62871:5432'
    volumes:
      - db-prod:/var/lib/postgresql/data
volumes:
  db-prod:
    driver: local