{
 "title": "Electricity Consumption",
 "time": { "from": "2023-02-07T23:00:00.000Z", "to": "2023-05-31T09:50:52.893Z" },
 "panels": [
  {
   "title": "Consumption per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT consumption, datetime FROM {EN_TABLE_NAME};"
    }
   ]
  },
  {
   "title": "Last measured day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT data.consumption, to_char(data.time, 'DD-MM HH24:00') as hour\nFROM (\n  SELECT datetime at time zone 'Europe/Madrid' as time, consumption as consumption\n  FROM {EN_TABLE_NAME}\n  ORDER BY datetime DESC\n  LIMIT 24) as data\nORDER BY data.time ASC;"
    }
   ]
  },
  {
   "title": "Daily Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('day', datetime), SUM(consumption) as daily_consumption\nFROM {EN_TABLE_NAME} \nGROUP BY DATE_TRUNC('day', datetime);"
    }
   ]
  },
  {
   "title": "Typical work day",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT to_char(datetime at time zone 'Europe/Madrid', 'HH24') as hour, \n      AVG(consumption)      \nFROM {EN_TABLE_NAME} \nWHERE EXTRACT(isodow FROM datetime at time zone 'Europe/Madrid') <= 5\nGROUP BY hour\nORDER BY hour;"
    }
   ]
  },
  {
   "title": "Weekly Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('week', datetime), SUM(consumption) as weekly_consumption\nFROM {EN_TABLE_NAME} \nGROUP BY DATE_TRUNC('week', datetime);"
    }
   ]
  },
  {
   "title": "Day of the week average",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  AVG(s.daily_cons) AS dow_average,\n        to_char(s.Date at time zone 'Europe/Madrid', 'DY')\nFROM    (   \n            SELECT  date_trunc('day', datetime, 'Europe/Madrid') AS Date, \n                    SUM(consumption) AS daily_cons\n            FROM {EN_TABLE_NAME}\n            GROUP BY date_trunc('day', datetime, 'Europe/Madrid')\n        ) AS s\nGROUP BY to_char(s.Date at time zone 'Europe/Madrid', 'DY')\nORDER BY dow_average\n--CASE\n--          WHEN to_char(s.Date, 'DY') = 'MON' THEN 1\n--          WHEN to_char(s.Date, 'DY') = 'TUE' THEN 2\n--          WHEN to_char(s.Date, 'DY') = 'WED' THEN 3\n--          WHEN to_char(s.Date, 'DY') = 'THU' THEN 4\n--          WHEN to_char(s.Date, 'DY') = 'FRI' THEN 5\n--          WHEN to_char(s.Date, 'DY') = 'SAT' THEN 6\n--          WHEN to_char(s.Date, 'DY') = 'SUN' THEN 7\n--     END ASC\n;\n  "
    }
   ]
  },
  {
   "title": "Typical week-end day",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT to_char(datetime at time zone 'Europe/Madrid', 'HH24') as hour, \n      AVG(consumption)\nfrom {EN_TABLE_NAME} \nWHERE EXTRACT(isodow FROM datetime at time zone 'Europe/Madrid') >=6\nGROUP BY hour\nORDER BY hour;"
    }
   ]
  }
 ]
}